'use strict';
const $=id=>document.getElementById(id),K=(q,r)=>q+','+r,D=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs((a.q+a.r)-(b.q+b.r))),R=(a,b)=>Math.floor(Math.random()*(b-a+1))+a;
const S={log:[],day:1,hunger:100,maxHunger:100,life:100,maxLife:100,food:0,grass:0,wood:0,stone:0,fur:0,red:0,blue:0,yellow:0,fac:{base:0,kitchen:0,weapon:0,armor:0},compass:false,pos:{q:0,r:0},tiles:new Map(),book:{},special:{forest:null,pond:null,rock:null,cave:null},treasure:null,pending:null};
const T={grass:{name:'草原',icon:'🌿',food:[1,1],grass:[1,2],damage:0,rare:['レア食料',4]},forest:{name:'森',icon:'🌲',wood:[2,4],damage:5,rare:['毛皮',1]},rock:{name:'岩場',icon:'⛰️',stone:[2,4],damage:5,rare:['赤い宝石',1]},pond:{name:'池',icon:'💧',food:[2,4],damage:5,rare:['青い宝石',1]},cave:{name:'洞窟',icon:'🕳️',damage:20,rare:['黄色い宝石',1]},waste:{name:'荒地',icon:'🏜️',damage:0,rare:['レア食料',2]},sea:{name:'海',icon:'🌊',blocked:true,damage:0}};
const foods=[['fish','さかながぐつ','💧'],['otamame','おたまじゃくし豆','🫘'],['umashika','ウマシカ','🌲'],['kutsu','くつかぼちゃ','🌿'],['benri','荒地ベンリ菜','🏜️'],['denki','電気きのこ','🕳️']];
const costName={grass:'草',wood:'木材',stone:'石材',fur:'毛皮',red:'赤い宝石',blue:'青い宝石',yellow:'黄色い宝石'};
function toast(s){let e=$('toast');e.textContent=s;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1500)}
function gen(q,r){let k=K(q,r);if(S.tiles.has(k))return S.tiles.get(k);if(q===0&&r===0){let c={q,r,t:'grass',seen:true};S.tiles.set(k,c);return c}let d=D({q,r},S.pos),t='grass';if(d){let opts=[];if(!S.special.forest&&d>=2)opts.push(['forest',Math.exp(-((d-3)**2)/1.5)]);if(!S.special.pond&&d>=3)opts.push(['pond',Math.exp(-((d-4)**2)/1.5)]);if(!S.special.rock&&d>=4)opts.push(['rock',Math.exp(-((d-5)**2)/1.7)]);if(!S.special.cave&&d>=5)opts.push(['cave',.7*Math.exp(-((d-6)**2)/2)]);opts.sort((a,b)=>b[1]-a[1]);if(opts[0]&&Math.random()<opts[0][1]*.6){t=opts[0][0];S.special[t]=k}else if(Math.random()<.12)t='waste';else if(Math.random()<.05&&d>4)t='sea'}let c={q,r,t,seen:false};S.tiles.set(k,c);return c}
function init(){let ang=Math.random()*Math.PI*2,d=R(9,15);S.treasure={q:Math.round(Math.cos(ang)*d),r:Math.round(Math.sin(ang)*d)}}
function render(){ $('log').innerHTML=(S.log||[]).slice(0,6).map(x=>'<div class="log-item">'+x+'</div>').join(''); $('day').textContent=S.day;$('hungerText').textContent=S.hunger+' / '+S.maxHunger;$('lifeText').textContent=S.life+' / '+S.maxLife;$('hungerBar').style.width=(S.hunger/S.maxHunger*100)+'%';$('lifeBar').style.width=(S.life/S.maxLife*100)+'%';$('resources').innerHTML=`🪵 ${S.wood}　🪨 ${S.stone}　🍖 ${S.food}　🌿 ${S.grass}　🧥 ${S.fur}　🔴${S.red} 🔵${S.blue} 🟡${S.yellow}`;renderMap();renderFacilities();renderBook()}
function renderMap(){let m=$('map');m.innerHTML='';for(let q=-7;q<=7;q++)for(let r=-7;r<=7;r++){if(Math.abs(q+r)>7)continue;let c=gen(q,r),e=document.createElement('div'),x=300+q*84,y=350+r*70+q*35;e.className='hex '+(c.seen?'explored '+c.t:'unexplored')+(c.t==='sea'?' blocked':'')+(q===S.pos.q&&r===S.pos.r?' base':'');e.style.left=(x-43)+'px';e.style.top=(y-49)+'px';e.innerHTML=`<div class="inside"><div class="terrain-icon">${c.seen?T[c.t].icon:'?'}</div><div>${c.seen?T[c.t].name:'地形'}</div></div>`;if(c.t!=='sea'&&D(c,S.pos)===1){e.classList.add('available');e.onclick=()=>openExplore(c)}m.appendChild(e)}}
function preview(c){let d=T[c.t],a=[];if(d.food)a.push('🍖 食料 '+d.food[0]+'～'+d.food[1]);if(d.grass)a.push('🌿 草 '+d.grass[0]+'～'+d.grass[1]);if(d.wood)a.push('🪵 木材 '+d.wood[0]+'～'+d.wood[1]);if(d.stone)a.push('🪨 石材 '+d.stone[0]+'～'+d.stone[1]);if(d.damage)a.push('❤️ 地形ダメージ '+Math.floor(d.damage*(S.fac.weapon===2?.5:S.fac.weapon===1?.8:1)));a.push('✨ レア：'+d.rare[0]+' ×'+d.rare[1]+'（10%）');return a.join('<br>')}
function openExplore(c){let d=D(c,S.pos),cost=10+d*5,dam=Math.floor(T[c.t].damage*(S.fac.weapon===2?.5:S.fac.weapon===1?.8:1));S.pending={c,cost,dam};$('exploreTitle').textContent=T[c.t].name;$('explorePreview').innerHTML=`<div class="target-icon">${T[c.t].icon}</div><div>拠点から ${D(c,{q:0,r:0})} マス</div>`;$('travelCost').innerHTML=`🍖 空腹 -${cost}　❤️ ダメージ -${dam}${S.hunger<cost?'　⚠ 空腹不足分もライフ減少':''}`;$('resourcePreview').innerHTML=preview(c);$('exploreModal').hidden=false}
function closeModal(id){$(id).hidden=true}
function explore(){let p=S.pending,c=p.c,d=T[c.t];closeModal('exploreModal');$('char').textContent='🏃';setTimeout(()=>{$('char').textContent='👨‍💼';let shortage=Math.max(0,p.cost-S.hunger);S.hunger=Math.max(0,S.hunger-p.cost);S.life-=p.dam+shortage;if(d.food)S.food+=R(...d.food);if(d.grass)S.grass+=R(...d.grass);if(d.wood)S.wood+=R(...d.wood);if(d.stone)S.stone+=R(...d.stone);if(d.rare&&Math.random()<.1){let x=d.rare[0];if(x==='毛皮')S.fur++;if(x==='赤い宝石')S.red++;if(x==='青い宝石')S.blue++;if(x==='黄色い宝石')S.yellow++;if(x==='レア食料')S.food+=d.rare[1];toast('レア素材：'+x)}let fs=foods.filter(x=>x[2]===T[c.t].icon);if(fs.length&&Math.random()<.35)S.book[fs[R(0,fs.length-1)][0]]=1;c.seen=true;S.log.unshift('Day '+S.day+'　'+T[c.t].name+'を探索');S.pos={q:c.q,r:c.r};S.day++;if(c.q===S.treasure.q&&c.r===S.treasure.r){alert('秘宝を発見！ GAME CLEAR');location.reload();return}if(S.life<=0){alert('GAME OVER');location.reload();return}render()},3000)}
function eat(){if(!S.food)return toast('食料がありません');let n=S.fac.kitchen===2?15:S.fac.kitchen===1?12:10;S.food--;S.hunger=Math.min(S.maxHunger,S.hunger+n);$('char').textContent='🍖';setTimeout(()=>$('char').textContent='👨‍💼',700);render()}
const defs=[['base','拠点',[[5,0,0,0,0,0,0,'草5','藁のテント'],[10,10,0,0,0,0,0,'木材10＋石材10','小屋']]],['kitchen','食堂',[[5,0,0,0,0,0,0,'木材5','焚き火'],[10,0,1,0,0,0,0,'石材10＋赤い宝石1','電気鍋']]],['weapon','武器',[[5,0,0,0,0,0,0,'木材5','軽減20%'],[10,0,1,0,0,0,0,'石材10＋赤い宝石1','軽減50%']]],['armor','防具',[[5,0,0,0,0,0,0,'木材5','最大ライフ+20'],[10,0,1,0,0,0,0,'石材10＋赤い宝石1','最大ライフ+50']]]];
function can(a){return S.grass>=a[0]&&S.wood>=a[1]&&S.stone>=a[2]&&S.fur>=a[3]&&S.red>=a[4]&&S.blue>=a[5]&&S.yellow>=a[6]}function pay(a){S.grass-=a[0];S.wood-=a[1];S.stone-=a[2];S.fur-=a[3];S.red-=a[4];S.blue-=a[5];S.yellow-=a[6]}
function buildUI(){let h='';defs.forEach(d=>{let lv=S.fac[d[0]],n=lv+1;if(n<=2){let a=d[2][n-1],ok=n<=S.fac.base&&can(a);h+=`<div class="build-row"><div><h3>${d[1]} Lv${n}</h3><p>${a[7]} / ${a[8]}</p></div><button data-b="${d[0]}" ${ok?'':'disabled'}>建設</button></div>`}});h+=`<div class="build-row"><div><h3>冷蔵庫</h3><p>黄色1＋青3＋石材20 / 空腹最大+50</p></div><button id="fridge" ${S.maxHunger>100||S.yellow<1||S.blue<3||S.stone<20?'disabled':''}>建設</button></div><div class="build-row"><div><h3>コンパス</h3><p>黄色1＋青1＋赤1 / 秘宝マス表示</p></div><button id="compass" ${S.compass||S.yellow<1||S.blue<1||S.red<1?'disabled':''}>建設</button></div>`;$('buildList').innerHTML=h;$('buildModal').hidden=false;document.querySelectorAll('[data-b]').forEach(b=>b.onclick=()=>build(b.dataset.b));$('fridge').onclick=()=>{S.yellow--;S.blue-=3;S.stone-=20;S.maxHunger=150;render();buildUI()};$('compass').onclick=()=>{S.yellow--;S.blue--;S.red--;S.compass=true;toast('秘宝マスが分かるようになった');render();buildUI()}}
function build(id){let d=defs.find(x=>x[0]===id),n=S.fac[id]+1,a=d[2][n-1];if(n>S.fac.base||!can(a))return;pay(a);S.fac[id]=n;if(id==='armor'){S.maxLife=n===1?120:150}render();buildUI();toast(d[1]+' Lv'+n)}
function renderFacilities(){$('facilities').innerHTML=defs.map(d=>`<div class="facility"><div class="icon">${d[1]}</div><h3>Lv${S.fac[d[0]]}</h3></div>`).join('')}
function renderBook(){$('book').innerHTML=foods.map(f=>`<div class="book-card ${S.book[f[0]]?'':'locked'}"><div class="food-art">${S.book[f[0]]?f[2]:'?'}</div><div>${S.book[f[0]]?f[1]:'？？？'}</div></div>`).join('')}
$('start').onclick=()=>{$('title').hidden=true;$('game').hidden=false;init();render()};$('eat').onclick=eat;$('confirmExplore').onclick=explore;$('modalClose').onclick=()=>closeModal('exploreModal');$('cancelExplore').onclick=()=>closeModal('exploreModal');$('buildBtn').onclick=buildUI;$('bookBtn').onclick=()=>{$('bookModal').hidden=false;renderBook()};$('clearLog').onclick=()=>{$('log').innerHTML=''};document.querySelectorAll('.modalClose2').forEach(b=>b.onclick=()=>b.closest('.modal-backdrop').hidden=true);
