'use strict';
const state={day:1,hunger:100,maxHunger:100,life:100,maxLife:100,wood:12,stone:8,food:5,herb:0,weapon:0,armor:0,log:[],tiles:{},facilities:{campfire:1,pot:0,fridge:0,workbench:0,storage:0}};
const terrain={forest:{name:'森',icon:'🌲',fixed:{wood:10,food:1},rare:[{name:'薬草',icon:'🌿',chance:.18}]},mountain:{name:'岩場',icon:'⛰️',fixed:{stone:8},rare:[{name:'鉄鉱石',icon:'⛏️',chance:.15}]},grass:{name:'草原',icon:'🌿',fixed:{food:2,herb:1},rare:[{name:'珍しい植物',icon:'🌱',chance:.12}]},water:{name:'水辺',icon:'🌊',fixed:{food:1},rare:[{name:'珍しい食料',icon:'🍓',chance:.12}]},cave:{name:'洞窟',icon:'🕳️',fixed:{stone:12},rare:[{name:'レア鉱石',icon:'💎',chance:.22}]}};
const coords=[];for(let q=-2;q<=2;q++){for(let r=-2;r<=2;r++){if(Math.abs(q+r)<=3)coords.push({q,r});}}
const key=(q,r)=>`${q},${r}`;const dist=(a,b)=>Math.max(Math.abs(a.q-b.q),Math.abs(a.r-b.r),Math.abs((a.q+a.r)-(b.q+b.r)));const base={q:0,r:0};state.tiles[key(0,0)]={type:'base',explored:true};
function seedMap(){coords.forEach(c=>{if(key(c.q,c.r)==='0,0')return;const n=Math.abs(c.q*13+c.r*7)%10;const type=n<3?'forest':n<5?'grass':n<7?'mountain':n<9?'water':'cave';state.tiles[key(c.q,c.r)]={type,explored:false};});}seedMap();
function neighbors(c){return coords.filter(x=>dist(c,x)===1)}function isAvailable(c){return !state.tiles[key(c.q,c.r)].explored&&neighbors(c).some(n=>state.tiles[key(n.q,n.r)]?.explored)}
function render(){
 document.querySelector('#day').textContent=`Day ${state.day}`;document.querySelector('#hungerText').textContent=`${state.hunger} / ${state.maxHunger}`;document.querySelector('#lifeText').textContent=`${state.life} / ${state.maxLife}`;
 document.querySelector('#hungerBar').style.width=`${state.hunger/state.maxHunger*100}%`;document.querySelector('#lifeBar').style.width=`${state.life/state.maxLife*100}%`;
 document.querySelector('#resources').innerHTML=`<span class="res">🪵 ${state.wood}</span><span class="res">🪨 ${state.stone}</span><span class="res">🍖 ${state.food}</span><span class="res">🌿 ${state.herb}</span>`;
 document.querySelector('#characterFood').textContent=state.food;renderMap();renderFacilities();renderLog();updateMood();
}
function renderMap(){const el=document.querySelector('#map');el.innerHTML='';const cx=195,cy=170,w=112,h=129;coords.forEach(c=>{const t=state.tiles[key(c.q,c.r)],x=cx+c.q*(w*.75),y=cy+c.r*(h*.75)+c.q*(h*.375),available=isAvailable(c);const node=document.createElement('div');node.className=`hex ${t.explored?'explored '+t.type:'unexplored'} ${available?'available':''} ${t.type==='base'?'base':''}`;node.style.left=`${x-w/2}px`;node.style.top=`${y-h/2}px`;if(t.explored)node.innerHTML=`<div class="inside"><div class="terrain-icon">${t.type==='base'?'🏕️':terrain[t.type].icon}</div><div>${t.type==='base'?'拠点':terrain[t.type].name}</div></div>`;else if(available)node.innerHTML=`<div class="inside"><div class="terrain-icon">${terrain[t.type].icon}</div><div>${terrain[t.type].name}</div></div>`;else node.innerHTML='<div class="inside">?</div>';if(available)node.onclick=()=>openExploreModal(c);el.appendChild(node);});}
let selectedTile=null;function getHungerCost(c){return 8+dist(base,c)*5}function getDamagePreview(c){const t=state.tiles[key(c.q,c.r)],d=dist(base,c);if(['mountain','cave'].includes(t.type))return Math.max(0,8+Math.floor(d*3)-state.weapon*4);if(t.type==='water')return Math.max(0,4-state.weapon*2);return 0}
function itemName(k){return({wood:'木材',stone:'石',food:'食料',herb:'薬草'})[k]||k}function resourceIcon(k){return({wood:'🪵',stone:'🪨',food:'🍖',herb:'🌿'})[k]||'📦'}
function openExploreModal(c){if(!isAvailable(c))return;selectedTile=c;const t=state.tiles[key(c.q,c.r)],d=dist(base,c),hungerCost=getHungerCost(c),damage=getDamagePreview(c);document.querySelector('#exploreTitle').textContent=terrain[t.type].name;document.querySelector('#explorePreview').innerHTML=`<div class="target-icon">${terrain[t.type].icon}</div><div class="target-info"><strong>拠点から ${d} マス</strong><span>${d===1?'近距離':d===2?'中距離':'遠距離'}の探索先</span></div>`;document.querySelector('#travelCost').innerHTML=`<span class="cost-pill hunger-cost">🍖 空腹度 <b>-${hungerCost}</b></span>${damage?`<span class="cost-pill damage-cost">❤️ 予想ダメージ <b>-${damage}</b></span>`:'<span class="cost-pill safe-cost">✓ 戦闘ダメージなし</span>'}`;const fixed=t.type==='base'?{}:terrain[t.type].fixed;const fixedHtml=Object.entries(fixed).map(([k,v])=>`<div class="resource-chip"><span>${resourceIcon(k)}</span><b>${itemName(k)} ×${v}</b><small>確定</small></div>`).join('');const rareHtml=(terrain[t.type].rare||[]).map(r=>`<div class="resource-chip rare-chip"><span>${r.icon}</span><b>${r.name} ×1</b><small>レア・ランダム</small></div>`).join('');document.querySelector('#resourcePreview').innerHTML=fixedHtml+rareHtml;document.querySelector('#resourceNote').textContent='※確定資源は必ず入手。レア素材は表示されたものが一定確率で出現します。';document.querySelector('#exploreModal').hidden=false;requestAnimationFrame(()=>document.querySelector('#exploreModal').classList.add('show'));}
function closeExploreModal(){const m=document.querySelector('#exploreModal');m.classList.remove('show');setTimeout(()=>{m.hidden=true;selectedTile=null},160)}function confirmExplore(){if(!selectedTile)return;const c=selectedTile;closeExploreModal();explore(c)}
function explore(c){if(!isAvailable(c))return;const t=state.tiles[key(c.q,c.r)],hungerCost=getHungerCost(c);animateCharacter('explore');state.hunger-=hungerCost;const dmg=getDamagePreview(c);state.life-=dmg;const got=[];Object.entries(terrain[t.type].fixed).forEach(([k,v])=>{state[k]+=v;got.push(`${itemName(k)} ×${v}`)});for(const rare of terrain[t.type].rare||[]){if(Math.random()<rare.chance){if(rare.name.includes('鉄')||rare.name.includes('鉱')){state.stone+=3}else if(rare.name.includes('薬草')||rare.name.includes('植物')){state.herb++}else{state.food++}got.push(`${rare.name} ×1`)}}t.explored=true;state.log.unshift(`Day ${state.day}　${terrain[t.type].name}を探索。${got.join('、')}${dmg?`　ダメージ -${dmg}`:''}`);nextDay()}
function nextDay(){if(state.hunger<=0){state.hunger=0;state.life-=12;state.log.unshift('空腹で体力を消耗した！ ライフ -12')}state.day++;render();if(state.life<=0){state.life=0;setTimeout(()=>alert('GAME OVER\nこの世界で力尽きました。'),50)}}
const facilityData=[{id:'campfire',name:'焚き火',icon:'🔥',desc:'夜を越えるための基本設備',cost:null},{id:'pot',name:'鍋',icon:'🍲',desc:'食料1個の空腹回復量 +10',cost:{wood:10,stone:6},max:1},{id:'fridge',name:'冷蔵庫',icon:'🧊',desc:'空腹度の最大値 +30',cost:{wood:20,stone:10},max:1},{id:'workbench',name:'作業台',icon:'🪚',desc:'武器・防具を作れるようになる',cost:{wood:15,stone:8},max:1},{id:'storage',name:'倉庫',icon:'📦',desc:'資源を保管する拠点設備',cost:{wood:15,stone:10},max:1},{id:'weapon',name:'武器',icon:'⚔️',desc:'探索時のダメージを軽減',cost:{wood:12,stone:12},max:1},{id:'armor',name:'防具',icon:'🛡️',desc:'最大ライフ +40',cost:{wood:18,stone:14},max:1}];
function renderFacilities(){const el=document.querySelector('#facilities');el.innerHTML='';facilityData.forEach(f=>{const lv=state.facilities[f.id]||0;const unlocked=f.id==='campfire'||state.facilities.workbench||['pot','fridge','workbench','storage'].includes(f.id);const div=document.createElement('div');div.className=`facility${!unlocked?' locked':''}`;div.innerHTML=`<div class="icon">${unlocked?f.icon:'🔒'}</div><h3>${unlocked?f.name:'未開放'}</h3><p>${unlocked?f.desc:'作業台を開発すると開放'}</p>${unlocked&&f.cost?`<button ${lv?'disabled':''}>${lv?'開発済み':'開発'}<br>${costText(f.cost)}</button>`:''}`;const btn=div.querySelector('button');if(btn)btn.onclick=()=>upgrade(f);el.appendChild(div)})}
function costText(c){return Object.entries(c).map(([k,v])=>`${itemName(k)} ${v}`).join(' / ')}function upgrade(f){if(Object.entries(f.cost).some(([k,v])=>state[k]<v)){toast('資源が足りません');return}Object.entries(f.cost).forEach(([k,v])=>state[k]-=v);state.facilities[f.id]=1;if(f.id==='fridge')state.maxHunger+=30;if(f.id==='weapon')state.weapon=1;if(f.id==='armor')state.maxLife+=40;state.hunger=Math.min(state.hunger,state.maxHunger);state.life=Math.min(state.life,state.maxLife);state.log.unshift(`${f.name}を開発した！`);toast(`${f.name}を開発しました`);render()}
function renderLog(){document.querySelector('#log').innerHTML=state.log.slice(0,5).map(x=>`<div class="log-item">${x}</div>`).join('')||'<div>まだ探索記録はありません。</div>'}function toast(msg){const e=document.querySelector('#toast');e.textContent=msg;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1600)}
function updateMood(){const m=document.querySelector('#characterMood');if(state.hunger<=15)m.textContent='「もう限界だ……」';else if(state.hunger<=35)m.textContent='「腹……減った……」';else if(state.hunger>=80)m.textContent='「よし、まだ動ける」';else m.textContent='「さて、次はどこへ行くか」'}
function animateCharacter(type){const c=document.querySelector('#character');c.classList.remove('explore','eat','hit');void c.offsetWidth;c.classList.add(type);setTimeout(()=>c.classList.remove(type),type==='explore'?1800:1000)}
function openFoodModal(){renderFoodChoices();const m=document.querySelector('#foodModal');m.hidden=false;requestAnimationFrame(()=>m.classList.add('show'));document.querySelector('#character').classList.add('selected')}
function closeFoodModal(){const m=document.querySelector('#foodModal');m.classList.remove('show');document.querySelector('#character').classList.remove('selected');setTimeout(()=>m.hidden=true,160)}
function renderFoodChoices(){const el=document.querySelector('#foodChoices');el.innerHTML='';if(state.food<=0){el.innerHTML='<div class="empty-food">食料を持っていません。</div>';return}const restore=10+state.facilities.pot*10;const maxEat=Math.min(state.food,Math.max(1,Math.ceil((state.maxHunger-state.hunger)/restore)));const btn=document.createElement('button');btn.className='food-choice';btn.innerHTML=`<span class="food-icon">🍖</span><span><b>食料 ×1</b><small>空腹度 +${restore}</small></span><strong>${state.food}</strong>`;btn.onclick=()=>eatFood(1);el.appendChild(btn);if(maxEat>1){const all=document.createElement('button');all.className='food-choice';all.innerHTML=`<span class="food-icon">🍖🍖</span><span><b>満腹まで食べる</b><small>最大 ${maxEat} 個 / +${Math.min(maxEat*restore,state.maxHunger-state.hunger)}</small></span><strong>${maxEat}</strong>`;all.onclick=()=>eatFood(maxEat);el.appendChild(all)}}
function eatFood(amount){if(state.food<=0||state.hunger>=state.maxHunger){toast(state.hunger>=state.maxHunger?'もう満腹です':'食料がありません');return}const restore=10+state.facilities.pot*10;const actual=Math.min(amount,state.food,Math.ceil((state.maxHunger-state.hunger)/restore));state.food-=actual;state.hunger=Math.min(state.maxHunger,state.hunger+actual*restore);state.log.unshift(`食料を${actual}個食べた。空腹度 +${actual*restore}`);closeFoodModal();animateCharacter('eat');toast(`お腹が満たされた +${actual*restore}`);render()}
document.querySelector('#characterPanel').onclick=openFoodModal;document.querySelector('#characterPanel').onkeydown=e=>{if(e.key==='Enter'||e.key===' ')openFoodModal()};document.querySelector('#clearLog').onclick=()=>{document.querySelector('#log').innerHTML='';};document.querySelector('#modalClose').onclick=closeExploreModal;document.querySelector('#cancelExplore').onclick=closeExploreModal;document.querySelector('#confirmExplore').onclick=confirmExplore;document.querySelector('#exploreModal').addEventListener('click',e=>{if(e.target.id==='exploreModal')closeExploreModal()});document.querySelector('#foodClose').onclick=closeFoodModal;document.querySelector('#foodCancel').onclick=closeFoodModal;document.querySelector('#foodModal').addEventListener('click',e=>{if(e.target.id==='foodModal')closeFoodModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!document.querySelector('#exploreModal').hidden)closeExploreModal();if(!document.querySelector('#foodModal').hidden)closeFoodModal()}});render();
